language: java
sudo: true

before_install:
  - chmod +x mvnw

addons:
  sonarcloud:
    organization: "ivan2yk-github" # the key of the org you chose at step #3
    token:
      secure: '$SONAR_TOKEN'

jdk:
  - oraclejdk8

script:
 # JaCoCo is used to have code coverage, the agent has to be activated
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'